# Generated by Django 6.0.2 on 2026-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_order_status_product_is_available_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/tab.png', upload_to='products/'),
        ),
    ]
