# Generated by Django 4.2.30 on 2026-06-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_alter_product_image'),
        ('bakery', '0004_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
    ]
