# Generated by Django 5.0.14 on 2026-06-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_rename_pickup_date_order_pickup_availability_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('product_create', 'Product Created'), ('product_edit', 'Product Edited'), ('product_delete', 'Product Deleted'), ('order_status_update', 'Order Status Updated'), ('staff_create', 'Staff Account Created'), ('staff_edit', 'Staff Account Edited'), ('staff_deactivate', 'Staff Account Deactivated'), ('staff_activate', 'Staff Account Activated'), ('stock_validation_failed', 'Stock Validation Failed'), ('per_product_limit_failed', 'Per-Product Limit Failed'), ('cart_capacity_failed', 'Cart Capacity Failed'), ('order_cooldown_failed', 'Order Cooldown Failed'), ('daily_order_limit_failed', 'Daily Order Limit Failed'), ('cart_add_error', 'Cart Add Error'), ('order_created', 'Order Created'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_verification_failed', 'Payment Verification Failed'), ('pickup_completed', 'Pickup Completed'), ('stock_deducted', 'Stock Deducted'), ('stock_insufficient', 'Stock Insufficient')], max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('deduction', 'Stock Deduction'), ('restock', 'Stock Restock'), ('adjustment', 'Stock Adjustment'), ('initial', 'Initial Stock')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='bakery.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
