# Generated by Django 5.0.14 on 2026-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_alter_auditlog_action_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('claimed', 'Claimed'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
