# Generated by Django 6.0.6 on 2026-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_merge_20260612_1425'),
        ('bakery', '0010_order_claimed_at_order_processed_at'),
    ]

    operations = [
    ]
