# Generated by Django 6.0.6 on 2026-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_merge_20260614_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Customer contact number', max_length=11, null=True),
        ),
    ]
