# Generated by Django 6.0.6 on 2026-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_order_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of this item in the order'),
        ),
    ]
